### ISSUE TITLE
NPM Install?

### ISSUE THREAD

**Issue by melanke** [danielgindi/jquery-backstretch#12]
I've noticed that you put the 'main' section in the package.json
but it is not registered on npm, how do I install it?

**Comment by melanke** [comment]
https://www.npmjs.com/package/jquery.backstretch
If you want to contact me... my github is kind of busy, so find me at twitter @melanke

**Comment by danielgindi** [comment]
Hi @melanke, you are somehow the owner of the `npm` package, can you please publish 2.1.2?

This will close #16 & #17

**Comment by melanke** [comment]
I've just published it and added you as owner of the npm package
`npm owner add danielgindi`

But I could not found srobbin

**Comment by danielgindi** [comment]
Thanks!
