### ISSUE TITLE
"Pause" method doesn't work

### ISSUE THREAD

**Issue by chrisalcantara** [danielgindi/jquery-backstretch#15]
Hey, @danielgindi.

Whenever I pause the slideshow, I get an error that says: 
Error: `GET http://localhost:8000/pause 404 (NOT FOUND)`.

It seems the code is trying to pause the slideshow via the url? Not sure if that's suppose to happen. 

I assigned the pause to a click event. 

Basic code:
`$('.foo').backstretch([
 'path/to/image.jpg',
  'path/to/image2.jpg',
  'path/to/image3.jpg'
]);`

`$('button').click(function(event) {
    $('.foo').backstretch("pause")
});`

Thanks for keeping this project alive!

**Comment by psymeon** [comment]
I can confirm this, too. Actually all of the Slideshow API methods seem to have the same issue.
