### ISSUE TITLE
2.1.2 version isn't published in npm registry yet

### ISSUE THREAD

**Issue by dearlordylord** [danielgindi/jquery-backstretch#16]
Is there particular reason for it?

Thanks for maintaining it by the way :+1:

**Comment by danielgindi** [comment]
I can't publish to `npm` on the same `jquery.backstretch` package, as it is not originally published by me. I'll have to choose a new name. Any suggestions? 

#17

**Comment by danielgindi** [comment]
I see that `melanke` published my 2.1.1 version somehow to npm. I don't know how that happened.

**Comment by danielgindi** [comment]
Published!
