### ISSUE TITLE
Publish plugin to CDN

### ISSUE THREAD

**Issue by Ky7m** [danielgindi/jquery-backstretch#19]
Do you have plans to publish plugin to CDN, for example to cdn.js.
Previous version is here https://cdnjs.com/libraries/jquery-backstretch

**Comment by KhanMaytok** [comment]
:+1:

**Comment by danielgindi** [comment]
https://github.com/cdnjs/cdnjs/issues/7296

**Comment by Ky7m** [comment]
Thanks! It is deployed.
https://cdnjs.com/libraries/danielgindi-jquery-backstretch
