### ISSUE TITLE
Add blurred edge to images

### ISSUE THREAD

**Issue by AverageJ0E** [danielgindi/jquery-backstretch#22]
I'd like to add blur to my images. I use Backstretch as a block element. So I need to add some code to the backstretch.min.js. I am still running v2.0.4

I found if I add box-shadow: 0 0 8px 8px white inset; to class=backstretch it should work. My problem is, I can't figure out how to add it to it. My Javascript editing skills suck!

I referenced https://jsfiddle.net/d9Q5H/1/ to try the blurred image edge.

Any help would be appreciated!

Thanks!
AverageJoe

**Comment by danielgindi** [comment]
First of all - it's not Java. It's Javascript.
Second - You need not touch any JS. Do it in your CSS file.

**Comment by AverageJ0E** [comment]
Yes I know that! But I see the .css is inside the backstretch.js file. I don't see any .css files with this. I have tried to add it to the element before the backstretch in my site .css, but it won't override what backstretch is sending. I'd appreciate any help on this. but there doesn't appear to be an easy way to override the .css that is being set by backstretch.js. 

Thanks!

**Comment by danielgindi** [comment]
It does not come with any css files. You need to modify your own css file of your site
