### ISSUE TITLE
Zepto compatible plugin?

### ISSUE THREAD

**Issue by pwFoo** [danielgindi/jquery-backstretch#25]
I use [srobbin jquery-backstretch](https://github.com/srobbin/jquery-backstretch) and like it, but **automatic resolution selection** sounds like a great improvement to the plugin.

Because it's increased from 4kb to 16kb and I found the [zepto compatible fork](https://github.com/fiatjaf/zepto-backstretch)...

Is your plugin zepto compatible?

**Comment by danielgindi** [comment]
zepto should be jQuery compatible, that's the idea of it. I did not test compatibility with it, and some features of jQuery are not implemented in Zepto, but I do not see any reason why it won't work.

If you find issues - you are welcome to open a PR.
