### ISSUE TITLE
Input and zoom issue

### ISSUE THREAD

**Issue by vadimshvetsov** [danielgindi/jquery-backstretch#27]
Hi, Daniel!

Thank you a lot for updating the plugin. I've got an issue on focus on an input field from IPad. Backstretch resize the background image every time on focus input in Safari on my iPad. It's because keyboard was popping up and device height is changing, also got a problem on zoom, and when I zoom back - 
![image](https://cloud.githubusercontent.com/assets/16336572/17645607/c16e6560-61bb-11e6-9e2f-e637f49900d7.png)
![image](https://cloud.githubusercontent.com/assets/16336572/17645608/c19b1812-61bb-11e6-85c9-07207fbea745.png)

hidden part becomes white. Is any fix for it you know, or maybe it would be fixed in new updates?

Best Wishes, thank you!

**Comment by danielgindi** [comment]
Please check if your `html` element has a "100%" height. It should :-)

**Comment by vadimshvetsov** [comment]
Hello, Daniel!

Thank you a lot for response and fix that.

Did you update this cdn?
https://cdnjs.cloudflare.com/ajax/libs/danielgindi-jquery-backstretch/2.1.13/jquery.backstretch.js

**Comment by danielgindi** [comment]
There's no fix in the script, it's you who should fix your css...

**Comment by vadimshvetsov** [comment]
Oops. Checked and i've got html height and body property as 100%. But the issue still happens...

**Comment by danielgindi** [comment]
The you can try to debug your Mobile Safari with Safari on macOS, see what the sizes of the elements are etc. You can debug it like in Chrome's debugger

**Comment by vadimshvetsov** [comment]
Thanks for suggest, it's already done. The main bug happens when the iPad keyboard popups. In Safari on macOS i can't emulate keyboard popup.

**Comment by danielgindi** [comment]
You don't have to emulate it. You need to set your **mobile safari** into debug mode, and attach to a desktop safari. The desktop safari debugs the **mobile safari**.

**Comment by vadimshvetsov** [comment]
Ah, thank you. I will do this. May be the issue happens because I work in Coda for iPad and use internal browser in the application. Hope will resolve the problem. Thanks again.
