### ISSUE TITLE
VersionEye support

### ISSUE THREAD

**Issue by shehi** [danielgindi/jquery-backstretch#29]
Hi,

Could you please add VersionEye.com support for your package (registering it over at versioneye.com or whatever) so that our dependency checks cleared through them? Right now, my CI doesn't clear your package because of UNKNOWN license: 

https://www.versioneye.com/pullrequests/57bc6408f060a2000e6d1a5a

Regards.

**Comment by danielgindi** [comment]
I know nothing about VersionEye... You are welcome to configure it however you like.

**Comment by shehi** [comment]
You actually need to create an account there and just add your package. It is Github integrated, so will fetch everything you need to register there.

**Comment by danielgindi** [comment]
Done

**Comment by shehi** [comment]
LOL, drop VersionEye, switch to BitHound. They have security monitoring for dependencies, as well as version tracking. Took you awfully long to adapt this, which actually got outdated.

**Comment by danielgindi** [comment]
Well I don't really care about any of those, don't use them and probably not going too...
