### ISSUE TITLE
Possible to load images from html instead of inside the script

### ISSUE THREAD

**Issue by Paul-Morris** [danielgindi/jquery-backstretch#33]
Is there a way to get backstretch to load images from an html unordered list like a lot of sliders do? The reason I ask is that I would like to generate the html list with drupal or wordpress and then just run the javascript on the generated html. This way the list can be updated with a cms instead of manually editing the backstretch file

**Comment by danielgindi** [comment]
We're moving back to the main repo, after it came back from the dead. Everything is merged back there.
Please re-open the issue there :-)
