### ISSUE TITLE
Image resolution selection and 2x support

### ISSUE THREAD

**Issue by Gtoffo** [danielgindi/jquery-backstretch#6]
Hey,
thanks for keeping this alive.

Total noob here so be patient please. But I'm having problems with automatic resolution selection.

If I run the suggested code I run into this error: SyntaxError: Unexpected token ':'. Expected either a closing ']' or a ',' following an array element.
What am I missing?

Also, I'm having trouble understanding if the automatic resolution option takes into account the screen density of the user. A user with an iPhone might show a 750px screen but will require twice as many as the density is double. Is this supported or not yet?

Thanks.

**Comment by Gtoffo** [comment]
The code I'm using is the following:

 // Or, to automatically choose from a set of resolutions
  $(".foo").backstretch([
    [
      width: 1080, url: "path/to/image1_1080.jpg",
      width: 720, url: "path/to/image1_720.jpg",
      width: 320, url: "path/to/image1_320.jpg"
    ],
    [
      width: 1080, url: "path/to/image2_1080.jpg",
      width: 720, url: "path/to/image2_720.jpg",
      width: 320, url: "path/to/image2_320.jpg"
    ]
  ]);
</script>

 Which fails to load any images and gives error: SyntaxError: Unexpected token ':'. Expected either a closing ']' or a ',' following an array element.

Either the documentation is wrong or something in the script is broken.

**Comment by danielgindi** [comment]
I will test this soon. Something is probably broken there when handling
automatic resolution choice. You could also debug it.

**Comment by Gtoffo** [comment]
Also, should there be {} around each line?

[
{width: 1080, url: "path/to/image1_1080.jpg"},
{width: 720, url: "path/to/image1_720.jpg"},
{width: 320, url: "path/to/image1_320.jpg"}
],

**Comment by danielgindi** [comment]
Oh yes of course... The way you wrote in your first post is invalid JSON.

**Comment by Gtoffo** [comment]
Yep. Doesn't solve the issue though... something is wrong in the script itself.

**Comment by danielgindi** [comment]
Please the sample HTML in the latest version. It demonstrates that it works

**Comment by Gtoffo** [comment]
Thanks!
