### ISSUE TITLE
Bower repo update

### ISSUE THREAD

**Issue by bbashy** [danielgindi/jquery-backstretch#9]
Can you make it so we can pull in this library via bower instead of the other?

**Comment by danielgindi** [comment]
Well, the original repo is there, so we'd have to change its name.
You are welcome to handle the bower thing if you want to, I'm not really into bower...

**Comment by bbashy** [comment]
I'll submit a PR for the bower.json file and register it via bower. You can always unregister it with `bower unregister <package>`

**Comment by bbashy** [comment]
Need a new release version. The current has the bower.json error in it.

**Comment by danielgindi** [comment]
Done!

**Comment by bbashy** [comment]
Thanks a lot! I may do a PR for installing via bower (so people know what it's called).

> $ bower register jquery-backstretch-2 git://github.com/danielgindi/jquery-backstretch.git
> Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
> bower jquery-backstretch-2    register git://github.com/danielgindi/jquery-backstretch.git
> 
> Package jquery-backstretch-2 registered successfully!
> All valid semver tags on git://github.com/danielgindi/jquery-backstretch.git will be available as versions.
> To publish a new version, just release a valid semver tag.
> 
> Run bower info jquery-backstretch-2 to list the available versions.
